Repository rbuzzibarrios/calculator, pull requests merged in 2020-10, with the labels that each got.

#1 Initialize Calculator class
  application/models/Calculator.php
Labels: Initial Config, QA passed, enhancement

#2 Add /.idea to gitignore
  .gitignore
Labels: QA passed, enhancement

#3 Create php.yml
  .github/workflows/php.yml
  composer.json
  composer.lock
Labels: Initial Config, QA passed, enhancement

#4 Adding sum function
  application/models/Calculator.php
Labels: QA passed, enhancement

#6 Declaracion funcion multiplicar
  application/models/Calculator.php
Labels: QA passed, enhancement

#9 Declaracion funcion resta
  application/models/Calculator.php
Labels: QA passed, enhancement

#8 Create new Divide operation in Calculator Class
  application/Exceptions/DivideByZeroNotAllowedException.php
  application/Models/Calculator.php
Labels: QA passed, enhancement

#11 Make nullable second number attribute.
  application/Models/Calculator.php
  application/Traits/ValidateCalculatorNumberTrait.php
Labels: QA passed, enhancement

#12 Update Calculator sum description
  application/Models/Calculator.php
Labels: QA passed

#10 Implement square, cube and exponencial functions
  application/Models/Calculator.php
Labels: QA passed

#13 Adding/Implementing FizzBuzz class
  application/Models/Calculator.php
  application/Models/FizzBuzz.php
  application/Traits/ValidateCalculatorNumberTrait.php
Labels: QA passed
